development:
  sessions:
    default:
      database: try-github-flow_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: try-github-flow_test
      hosts:
        - localhost:27017